import type { Meetup } from "./types";

function isoInMinutes(minutesFromNow: number) {
  return new Date(Date.now() + minutesFromNow * 60_000).toISOString();
}

// 임시로 “서울 강남역 근처” 좌표로 몰아놓음(나중에 실제 위치로 교체)
const BASE = { lat: 37.4979, lng: 127.0276 };

export const MOCK_MEETUPS: Meetup[] = [
  {
    id: "m1",
    title: "퇴근 러닝 5K 같이해요",
    category: "running",
    startsAt: isoInMinutes(60),
    durationMin: 50,
    capacity: 6,
    joinedCount: 2,
    joinStatus: "none",
    placeName: "강남역 11번 출구",
    lat: BASE.lat + 0.002,
    lng: BASE.lng + 0.001,
    createdAt: isoInMinutes(-300),
  },
  {
    id: "m2",
    title: "점심 산책 30분",
    category: "walk",
    startsAt: isoInMinutes(180),
    durationMin: 30,
    capacity: 8,
    joinedCount: 5,
    joinStatus: "none",
    placeName: "테헤란로 공원",
    lat: BASE.lat - 0.001,
    lng: BASE.lng + 0.0005,
    createdAt: isoInMinutes(-200),
  },
  {
    id: "m3",
    title: "클라이밍 체험 (초보 환영)",
    category: "climb",
    startsAt: isoInMinutes(240),
    durationMin: 90,
    capacity: 4,
    joinedCount: 3,
    joinStatus: "none",
    placeName: "클라임짐 A",
    lat: BASE.lat + 0.0003,
    lng: BASE.lng - 0.0012,
    createdAt: isoInMinutes(-180),
  },
  {
    id: "m4",
    title: "헬스 PT 전 웜업 같이",
    category: "gym",
    startsAt: isoInMinutes(30),
    durationMin: 40,
    capacity: 3,
    joinedCount: 1,
    joinStatus: "none",
    placeName: "헬스장 B",
    lat: BASE.lat + 0.0011,
    lng: BASE.lng - 0.0003,
    createdAt: isoInMinutes(-120),
  },
  {
    id: "m5",
    title: "주말 가벼운 조깅",
    category: "running",
    startsAt: isoInMinutes(1440), // 내일
    durationMin: 60,
    capacity: 10,
    joinedCount: 6,
    joinStatus: "none",
    placeName: "한강공원(가까운 입구)",
    lat: BASE.lat - 0.0022,
    lng: BASE.lng - 0.0008,
    createdAt: isoInMinutes(-90),
  },
  {
    id: "m6",
    title: "집앞 스트레칭 + 걷기",
    category: "walk",
    startsAt: isoInMinutes(15),
    durationMin: 25,
    capacity: 5,
    joinedCount: 5,
    joinStatus: "none",
    placeName: "우리동네 놀이터",
    lat: BASE.lat - 0.0008,
    lng: BASE.lng + 0.0014,
    createdAt: isoInMinutes(-60),
  },
  {
    id: "m7",
    title: "가벼운 배드민턴?",
    category: "etc",
    startsAt: isoInMinutes(120),
    durationMin: 60,
    capacity: 6,
    joinedCount: 0,
    joinStatus: "none",
    placeName: "체육관 C",
    lat: BASE.lat + 0.0016,
    lng: BASE.lng + 0.0019,
    createdAt: isoInMinutes(-30),
  },
];
